[2023-01-08T23:09:50.961+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: UK_Accidents_2020-DAG.Extract_figures manual__2023-01-08T23:08:42.250284+00:00 [queued]>
[2023-01-08T23:09:50.992+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: UK_Accidents_2020-DAG.Extract_figures manual__2023-01-08T23:08:42.250284+00:00 [queued]>
[2023-01-08T23:09:50.992+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-08T23:09:50.992+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-08T23:09:50.993+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-08T23:09:51.034+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): Extract_figures> on 2023-01-08 23:08:42.250284+00:00
[2023-01-08T23:09:51.045+0000] {standard_task_runner.py:55} INFO - Started process 1032 to run task
[2023-01-08T23:09:51.059+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'UK_Accidents_2020-DAG', 'Extract_figures', 'manual__2023-01-08T23:08:42.250284+00:00', '--job-id', '379', '--raw', '--subdir', 'DAGS_FOLDER/flow.py', '--cfg-path', '/tmp/tmp8io7ehsb']
[2023-01-08T23:09:51.064+0000] {standard_task_runner.py:83} INFO - Job 379: Subtask Extract_figures
[2023-01-08T23:09:51.230+0000] {task_command.py:389} INFO - Running <TaskInstance: UK_Accidents_2020-DAG.Extract_figures manual__2023-01-08T23:08:42.250284+00:00 [running]> on host 3ad66d2ac9a1
[2023-01-08T23:09:51.448+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=UK_Accidents_2020-DAG
AIRFLOW_CTX_TASK_ID=Extract_figures
AIRFLOW_CTX_EXECUTION_DATE=2023-01-08T23:08:42.250284+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-08T23:08:42.250284+00:00
[2023-01-08T23:09:52.764+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (1,3,21) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-08T23:09:53.318+0000] {logging_mixin.py:137} INFO - Dash is running on http://0.0.0.0:3000/
[2023-01-08T23:09:53.318+0000] {dash.py:1968} INFO - Dash is running on http://0.0.0.0:3000/

[2023-01-08T23:09:53.324+0000] {logging_mixin.py:137} INFO -  * Serving Flask app 'unusual_prefix_9ec0e168250492834ce1cef2e8f4595fed38ca57_flow'
[2023-01-08T23:09:53.324+0000] {logging_mixin.py:137} INFO -  * Debug mode: off
[2023-01-08T23:09:53.325+0000] {_internal.py:224} INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:3000
 * Running on http://172.21.0.3:3000
[2023-01-08T23:09:53.325+0000] {_internal.py:224} INFO - [33mPress CTRL+C to quit[0m
[2023-01-08T23:22:49.662+0000] {local_task_job.py:82} ERROR - Received SIGTERM. Terminating subprocesses
[2023-01-08T23:22:49.678+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 1032. PIDs of all processes in the group: [1032]
[2023-01-08T23:22:49.678+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 1032
[2023-01-08T23:22:49.679+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-01-08T23:22:50.085+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/flow.py", line 46, in task2_extract_figures
    app.run_server(host="localhost", port='7080', debug=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/dash/dash.py", line 2133, in run_server
    self.run(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/dash/dash.py", line 1980, in run
    self.server.run(host=host, port=port, debug=debug, **flask_run_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 1188, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/home/airflow/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 1098, in run_simple
    srv.serve_forever()
  File "/home/airflow/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 741, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
  File "/usr/local/lib/python3.7/socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "/usr/local/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-01-08T23:22:50.228+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=UK_Accidents_2020-DAG, task_id=Extract_figures, execution_date=20230108T230842, start_date=20230108T230950, end_date=20230108T232250
