[2023-01-08T23:01:33.844+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: UK_Accidents_2020-DAG.Extract_figures manual__2023-01-08T23:00:24.384469+00:00 [queued]>
[2023-01-08T23:01:33.854+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: UK_Accidents_2020-DAG.Extract_figures manual__2023-01-08T23:00:24.384469+00:00 [queued]>
[2023-01-08T23:01:33.854+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-08T23:01:33.855+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-08T23:01:33.855+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-08T23:01:33.929+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): Extract_figures> on 2023-01-08 23:00:24.384469+00:00
[2023-01-08T23:01:33.937+0000] {standard_task_runner.py:55} INFO - Started process 1060 to run task
[2023-01-08T23:01:33.942+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'UK_Accidents_2020-DAG', 'Extract_figures', 'manual__2023-01-08T23:00:24.384469+00:00', '--job-id', '376', '--raw', '--subdir', 'DAGS_FOLDER/flow.py', '--cfg-path', '/tmp/tmps3hl5kxu']
[2023-01-08T23:01:33.944+0000] {standard_task_runner.py:83} INFO - Job 376: Subtask Extract_figures
[2023-01-08T23:01:34.080+0000] {task_command.py:389} INFO - Running <TaskInstance: UK_Accidents_2020-DAG.Extract_figures manual__2023-01-08T23:00:24.384469+00:00 [running]> on host 3ad66d2ac9a1
[2023-01-08T23:01:34.364+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=UK_Accidents_2020-DAG
AIRFLOW_CTX_TASK_ID=Extract_figures
AIRFLOW_CTX_EXECUTION_DATE=2023-01-08T23:00:24.384469+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-08T23:00:24.384469+00:00
[2023-01-08T23:01:35.459+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (1,3,21) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-08T23:01:38.704+0000] {logging_mixin.py:137} INFO - Dash is running on http://0.0.0.0:8050/
[2023-01-08T23:01:38.704+0000] {dash.py:1968} INFO - Dash is running on http://0.0.0.0:8050/

[2023-01-08T23:01:38.721+0000] {logging_mixin.py:137} INFO -  * Serving Flask app 'unusual_prefix_9ec0e168250492834ce1cef2e8f4595fed38ca57_flow'
[2023-01-08T23:01:38.722+0000] {logging_mixin.py:137} INFO -  * Debug mode: off
[2023-01-08T23:01:38.723+0000] {_internal.py:224} INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8050
 * Running on http://172.21.0.3:8050
[2023-01-08T23:01:38.723+0000] {_internal.py:224} INFO - [33mPress CTRL+C to quit[0m
[2023-01-08T23:06:58.053+0000] {local_task_job.py:82} ERROR - Received SIGTERM. Terminating subprocesses
[2023-01-08T23:06:58.062+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 1060. PIDs of all processes in the group: [1060]
[2023-01-08T23:06:58.083+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 1060
[2023-01-08T23:06:58.096+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-01-08T23:06:58.157+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/flow.py", line 46, in task2_extract_figures
    app.run_server(host="0.0.0.0", port=3000, debug=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/dash/dash.py", line 2133, in run_server
    self.run(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/dash/dash.py", line 1980, in run
    self.server.run(host=host, port=port, debug=debug, **flask_run_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 1188, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/home/airflow/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 1098, in run_simple
    srv.serve_forever()
  File "/home/airflow/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 741, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
  File "/usr/local/lib/python3.7/socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "/usr/local/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-01-08T23:06:58.225+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=UK_Accidents_2020-DAG, task_id=Extract_figures, execution_date=20230108T230024, start_date=20230108T230133, end_date=20230108T230658
[2023-01-08T23:06:58.319+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 376 for task Extract_figures (Task received SIGTERM signal; 1060)
[2023-01-08T23:06:58.508+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1060, status='terminated', exitcode=1, started='23:01:33') (1060) terminated with exit code 1
[2023-01-08T23:06:58.510+0000] {local_task_job.py:159} INFO - Task exited with return code 143
[2023-01-08T23:06:58.974+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
