[2023-01-08T22:53:39.526+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: UK_Accidents_2020-DAG.Extract_figures manual__2023-01-08T22:52:09.830300+00:00 [queued]>
[2023-01-08T22:53:39.539+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: UK_Accidents_2020-DAG.Extract_figures manual__2023-01-08T22:52:09.830300+00:00 [queued]>
[2023-01-08T22:53:39.540+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-08T22:53:39.540+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-08T22:53:39.540+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-08T22:53:39.564+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): Extract_figures> on 2023-01-08 22:52:09.830300+00:00
[2023-01-08T22:53:39.571+0000] {standard_task_runner.py:55} INFO - Started process 2794 to run task
[2023-01-08T22:53:39.629+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'UK_Accidents_2020-DAG', 'Extract_figures', 'manual__2023-01-08T22:52:09.830300+00:00', '--job-id', '373', '--raw', '--subdir', 'DAGS_FOLDER/flow.py', '--cfg-path', '/tmp/tmpc964otb2']
[2023-01-08T22:53:39.653+0000] {standard_task_runner.py:83} INFO - Job 373: Subtask Extract_figures
[2023-01-08T22:53:39.743+0000] {task_command.py:389} INFO - Running <TaskInstance: UK_Accidents_2020-DAG.Extract_figures manual__2023-01-08T22:52:09.830300+00:00 [running]> on host 3ad66d2ac9a1
[2023-01-08T22:53:39.833+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=UK_Accidents_2020-DAG
AIRFLOW_CTX_TASK_ID=Extract_figures
AIRFLOW_CTX_EXECUTION_DATE=2023-01-08T22:52:09.830300+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-08T22:52:09.830300+00:00
[2023-01-08T22:53:41.344+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (1,3,21) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-08T22:53:41.727+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/flow.py", line 34, in task2_extract_figures
    fig = mpl_to_plotly(plt.plot(df["longitude"], df["latitude"], "o", ms=6, markevery=150))
  File "/home/airflow/.local/lib/python3.7/site-packages/plotly/tools.py", line 111, in mpl_to_plotly
    matplotlylib.Exporter(renderer).run(fig)
  File "/home/airflow/.local/lib/python3.7/site-packages/plotly/matplotlylib/mplexporter/exporter.py", line 46, in run
    if fig.canvas is None:
AttributeError: 'list' object has no attribute 'canvas'
[2023-01-08T22:53:41.806+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=UK_Accidents_2020-DAG, task_id=Extract_figures, execution_date=20230108T225209, start_date=20230108T225339, end_date=20230108T225341
[2023-01-08T22:53:41.945+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 373 for task Extract_figures ('list' object has no attribute 'canvas'; 2794)
[2023-01-08T22:53:42.052+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-08T22:53:42.188+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
